self.target = instance_find(obj_bed,0)
self.status = 2 //GML is mean and doesn't allow self.health
self.last_hit = noone
self.hit_timer = 200
self.speedval = 4
self.damage = 1
//self.image_xscale = 2
//self.image_yscale = 2
self.sound = sn_elite
self.sound_time = 300